### ISSUE TITLE
Collapsible Tree Structure

### ISSUE THREAD

**Issue by kc2188** [peaksandpies/yellowfin-jscharts#1]
HI,
I am trying to create Collapsible Tree Sturcture using Javascript in Yellowfin BI.
I am using d3 charts and can able to run the same using .html but not able to execute the script in Yellowfin bi.
and I am using data from database.
Here is the link I am refering to:
https://bl.ocks.org/mbostock/4339083

Can you please help me out?
Looking forward for your reply.

Thanks.

**Comment by pip77** [comment]
Hi,

I need some more information to help you. 
Which Yellowfin version are you using?
Could you be so kind and provide me your code, you have created inside yellowfin?
Can you see errors inside you browsers development console?

Best,
Phillip

**Comment by kc2188** [comment]
HI Philip,
thanks for the reply.
I am using Yellowfin 7.3+
Here is the code I am attaching.

[d3org.txt](https://github.com/peaksandpies/yellowfin-jscharts/files/1857305/d3org.txt)
[flare.json.txt](https://github.com/peaksandpies/yellowfin-jscharts/files/1857306/flare.json.txt)
Please guide me how to execute this in Yellowfin.
and more over data is coming from SQL Server not from Json.

Thanks,
Chandana K

**Comment by pip77** [comment]
Hello Chandana K,

have you already inserted the code inside a yellowfin report?

first of all you need to enable Javascript Charts inside Yellowfin as explained here http://wiki.yellowfin.com.au/display/USER73Plus/Enabling+JavaScript+Charts

After activating Javascript Charts, you start creating a new report inside yellowfin moving name, role and reports into the columns field in the data view. Then move to the Chart tab and choose Javascript as visualization. Here you can insert your Javascript and CSS code. We have also written a blog article showing an example. It is in german, but you can take a look at the screenshots and maybe try google transalate: https://peaksandpies.com/blog/2017/08/21/2017-08-21-javascript-charts-in-yellowfin/

Concerning you current code in d3org.txt: You still take your code from the .json file `d3.json("flare.json", function(error, flare) { ... }`. Yellowfin writes the data into into the variable `data` inside the function `doDrawing` (as you can see in the 3rd screenshot inside the german article).

Maybe you can provide me some screenshots from your yellowfin report.

Best,
Phillip

**Comment by kc2188** [comment]
Hi Philip,
Yeah I already enabled Javascript in Yellowfin and created Google Org Chart which is working fine (attached Org.txt for your reference).
But I couldnt able to generate the script for d3 charts.
as I am new to JavaScript, dont know how to write the code.
[org.txt](https://github.com/peaksandpies/yellowfin-jscharts/files/1858676/org.txt)

Please help me to solve the issue, I have to close the requirement today.

Thanks
Chandana

**Comment by kc2188** [comment]
HI Phillip,
Thanks for the reply.
Some how I managed to generate chart and it is working fine.
Only problem is when i execute the report instead of displaying first level only, it is expanding all at once.
Even though i wrote the function Collapse. Can you please check the script once and Let me know where the problem is?
Here I am attaching the Script.
[org.txt](https://github.com/peaksandpies/yellowfin-jscharts/files/1862834/org.txt)

Thanks
Chandana

**Comment by pip77** [comment]
Hello Chandana,

congrats! Just add a `chart.collapse(0, true);` after `chart.draw(data, {allowHtml:true, allowCollapse:true});`.

Best,
Phillip

**Comment by kc2188** [comment]
HI Phillip,
Thank you.
I tried that even, but still it is showing with all collapsible nodes.

Thanks,
Chandana

**Comment by kc2188** [comment]
HI Phillip,
Thanks for your support.
chart is working as per the requirement.

Thanks
Chandana

**Comment by pip77** [comment]
Hi Chandana,

sorry for the delayed answer, I was on easter vacation the last days. I am glad you made it.

Cheers,
Phillip
